#!/bin/bash

#This script checks the range of the number entered 
#by the user in [0 . 5]

echo "Enter a integer and press ENTER"

read num

if ($num -ge 0 && $num -le 5) then

else echo "The number is not a valid score"

fi
